AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  BookParserApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      Models:
        BookParsingRequest:
          type: object
          required:
            - url
          properties:
            url:
              type: string
  BookParserLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Handler: org.serverless.oqu.kerek.BookHandler::handleRequest
      CodeUri: build/distributions/oqu-kerek-app-0.1.0.zip
      Events:
        BookParserApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: post
            RequestModel:
              Model: BookParsingRequest
              Required: true
            RestApiId:
              Ref: BookParserApi
