AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  BookParserApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      Models:
        BookParsingRequest:
          type: object
          required:
            - url
          properties:
            url:
              type: string
  BookPagesUrlQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      DelaySeconds: 2
      MessageRetentionPeriod: 14400 # 4 hours
      QueueName: 'book-pages-url-queue'
      ReceiveMessageWaitTimeSeconds: 10
  BookParserLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Handler: org.serverless.oqu.kerek.BookHandler::handleRequest
      MemorySize: 512
      Timeout: 300
      CodeUri: build/distributions/oqu-kerek-app-0.1.0.zip
      Environment:
        Variables:
          QUEUE_NAME: !Ref BookPagesUrlQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BookPagesUrlQueue.QueueName
      Events:
        BookParserApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: post
            RequestModel:
              Model: BookParsingRequest
              Required: true
            RestApiId:
              Ref: BookParserApi
